server:
  port: 9222
  servlet:
    context-path: /

spring:
  application:
    name: vk-team-bot

vk-team-bot:
  token: "001.3431423473.1448932591:1011954462" # Токен сообщества VK Team
  chat-id: "AoLO5fFmNM4qLdK28wY"

logging:
  level:
    com.example.vkteambot: DEBUG